services:
  database:
    image: postgres
    container_name: database_compasso
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_DB=desafio_compasso
      - POSTGRES_USER=compasso
      - POSTGRES_PASSWORD=compasso
    volumes: 
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: desafio_compasso
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database
      
volumes: 
  postgres-data: